
// This file was generated by the template Settings.tt. Do not edit directly. Instead, edit the applciation's configuration file (App.config/Web.Config) and regenerate this code by right-clicking on the file and selecting "Run custom tool".    

namespace SetOMatic_Test
{
    using System;
    public static class Settings
    {
        public static bool IsLoaded{get; set;}

        static void Initialize(){}

        static Settings()
		{
            if (!IsLoaded)
                new SetOMatic().LoadSettings();
		}
        public static class appSettings
        {
            static appSettings()
		    {            
               Initialize();
		    }
            public static int test1 {get; internal set;}
            public static string test2 {get; internal set;}
            public static double test3 {get; internal set;}
            public static DateTime test4 {get; internal set;}
            public static string test5 {get; internal set;}
            public static string test6 {get; internal set;}
            public static string test_7 {get; internal set;}
        }
        public static class connectionStrings
        {
            static connectionStrings()
		    {            
               Initialize();
		    }
            public static string x_y_z {get; internal set;}
        }
        public static class CustomConnectionStrings
        {
            static CustomConnectionStrings()
		    {            
               Initialize();
		    }
            public static string Custom1 {get; internal set;}
        }
        public static class Section1
        {
            static Section1()
		    {            
               Initialize();
		    }
            public static string Test1 {get; internal set;}
        }
        public static class StranglyNamedSection1
        {
            static StranglyNamedSection1()
		    {            
               Initialize();
		    }
            public static string strange1 {get; internal set;}
        }
    }
}
